variables:
  JEKYLL_ENV: production
  SOURCE: $CI_PROJECT_DIR
  BUILD_DESTINATION: $CI_PROJECT_DIR/public
  GIT_PUSH_URL: https://$GITLAB_USER_LOGIN:$ACCESS_TOKEN@gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME.git
  GIT_PUSH_BRANCH: master:pages


jekyll_build:
  image: jekyll/jekyll:latest
  stage: build
  only:
    - master
  before_script:
    - jekyll -v
    - bundle install
  script:
    - jekyll build --source $SOURCE --destination $BUILD_DESTINATION
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  cache:
    paths:
      - /usr/local/bundle/

git_deploy:
  image: alpine:latest
  stage: deploy
  only:
    - master
  when: on_success
  before_script:
    - apk add --no-cache git
  script:
    - cd $BUILD_DESTINATION
    - git init
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git add --all
    - git commit -m "Deploy $CI_COMMIT_SHA"
    - git push --force --quiet $GIT_PUSH_URL $GIT_PUSH_BRANCH > /dev/null 2>&1
