# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: El blog de la ~virgulilla
lang: es
author: Roboe
email: web@virgulilla.com
description: > # this means to ignore newlines until "baseurl:"
  Crítica, filosofía y alfabetización digitales. La tecnología al servicio de la humanidad.
logo: /assets/images/logo.png

# Public web settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.virgulilla.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/
date_format: "%Y/%m/%d"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
  parse_span_html: true
  toc_levels: 2..6
sass:
  style: compressed
# plugins are fetched right from Gemfile's jekyll_plugins group
exclude: # dotfiles are excluded by default
  - Gemfile
  - Gemfile.lock

# Collection settings
collections:
  - rubiks
  - retrogaming

# Frontmatter defaults
defaults:
  - # Set default layout for posts
    scope:
      path: ""
      type: posts
    values:
      layout: post
  - # Set default layout for pages
    scope:
      path: ""
      type: pages
    values:
      layout: page
  - # Set default metadata image for jekyll-seo-tag
    scope:
      path: ""
    values:
      image: /assets/images/logo.png


# Social settings

## jekyll-seo-tag config
social:
  name: Roberto M.F.
  links:
    - https://twitter.com/RoboePi
    - https://gitlab.com/Roboe
    - https://github.com/Roboe

twitter:
  username: RoboePi
  link: https://twitter.com/RoboePi # not compatible with jekyll-seo-tag

## Using jekyll-seo-tag format for coherence
gitlab:
  username: Roboe
  link: https://gitlab.com/Roboe

github:
  username: Roboe
  link: https://github.com/Roboe
