# Site settings
title: El blog de la ~virgulilla
languageCode: es
params:
  description: >-
    Crítica, filosofía y alfabetización digitales. La tecnología al servicio de la humanidad.
  home:
    sections:
      - posts
      - articles
  author:
    firstName: Roberto #givenName
    lastName: MF #familyName
    displayName: Roboe
    #thumbnail:
    #image:
    #shortBio:
    #bio:
    email: web@virgulilla.com
    #weight:
    social:
      website: https://blog.virgulilla.com
      #facebook:
      gitlab: https://gitlab.com/Roboe
      github: https://github.com/Roboe
      twitter: https://twitter.com/RoboePi
      mastodon: https://mastodon.social/@RoboePi
      #googleplus:
      #pinterest:
      #instagram:
      #youtube:
      #linkedin:


# Public web settings
baseURL: https://blog.virgulilla.com
timezone: Europe/Madrid
defaultContentLanguage: es

permalinks:
  posts: /:year/:month/:day/:slug/
  articles: /:slug/

theme: virgulilla

disableKinds:
  - RSS

outputs:
  home:
    - HTML
    - Atom
  section:
    - HTML
    - Atom

# Build settings
blackfriday: # markdown processor
  smartypants: true # smart punctuation substitutions
  angledQuotes: true # render "quotes" as «quotes»
  fractions: false # render fractions with <sup> and <sub> tags
  smartDashes: false # translate -dashes- as &ndash; or &mdash;
  hrefTargetBlank: true # target="black" for absolute URLs
  nofollowLinks: true # rel="nofollow" for absolute URLs
  noreferrerLinks: true # rel="noreferrer" for absolute URLs
  plainIDAnchors: true # render headings and footnotes IDs without the document ID

# Privacy Settings
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
