# Site settings
title: El blog de la ~virgulilla
languageCode: es
params:
  description: >-
    Crítica, filosofía y alfabetización digitales. La tecnología al servicio de la humanidad.
  home:
    sections:
      - posts
      - articles


# Public web settings
baseURL: https://blog.virgulilla.com
timezone: Europe/Madrid
defaultContentLanguage: es

permalinks:
  posts: /:year/:month/:day/:slug/
  articles: /:slug/

frontmatter:
  date:
    - :filename
    - :default
  publishDate:
    - :default
    - :filename

theme:
  - virgulilla
  - webslides
  - revealjs

disableKinds:
  - RSS

outputs:
  home:
    - HTML
    - Atom
  section:
    - HTML
    - Atom

# Taxonomies
taxonomies:
  tag: tags
  category: categories
  author: authors

# Build settings
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true # smart punctuation substitutions
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true # render raw HTML
      xHTML: false

# Privacy Settings
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
