# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Reveal.js Theme Component"
license = "MIT"
licenselink = "https://gitlab.com/Roboe/hugo-revealjs-theme-component"
description = "Theme component for Reveal.js presentation framework"
homepage = "https://revealjs.com"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Roberto MF (Roboe)"
  homepage = "https://virgulilla.com"

# If porting an existing theme
[original]
  name = "Reveal.js"
  homepage = "https://revealjs.com"
  repo = "https://github.com/hakimel/reveal.js"
